version: "2"
run:
  tests: true
linters:
  enable:
    - forbidigo
    - gocritic
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
output:
  formats:
    tab:
      path: stdout
  show-stats: true
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
