run:
  timeout: 5m
  tests: true
issues:
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - whitespace
    - unparam
    - forbidigo
    - gocritic

output:
  formats:
    - format: tab
  show-stats: true