name: Terraform Test
on:
  pull_request:
    branches:
      - nshao/*

jobs:
  test:
    name: Run Terraform Unit Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::471112759938:role/cztack-ci
          role-session-name: TerraformTest

      - name: Install `terraform-test`
        run: |
          go install github.com/hashicorp/terraform-test@latest

      - name: Run Terraform Tests for All Modules
        run: |
          MODULES=$(find . -type f -name "*.tftest.hcl" -exec dirname {} \; | sort -u)

          for module in $MODULES; do
          echo "--- Running tests in: $module ---"
          cd "$module"

          # Run terraform test in the subdirectory
          terraform test

          # Navigate back to the root to find the next module
          cd -
          done
